### ISSUE TITLE
init file 

### ISSUE THREAD

**Issue by babuganesh2000** [Realsid/databricks-spark-certification#1]
at times I am having issues, on the init file
data.to_csv('/dbfs/tmp/df_some_sep', index=False, sep='$')

for some reason if my cluster do not have the folderdf_some_sep, it is throwing error

**Comment by Realsid** [comment]
The data mount from  databricks file system (dbfs/:) to local storage /dbfs has been disabled for community edition with databricks runtime version 7+ (DBR 7+). A quick hack would be to start a cluster with a DBR version 6+. I will change the code soon for DBR 7+
